# Generated by Django 2.2.13 on 2020-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=30)),
                ('blog_time', models.DateTimeField(auto_now_add=True)),
                ('blog_description', models.TextField()),
            ],
        ),
    ]
