# Generated by Django 2.2.13 on 2020-07-18 07:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
