# Generated by Django 2.2.13 on 2020-07-18 07:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200718_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
