# Generated by Django 2.2.13 on 2020-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
