# Generated by Django 2.2.13 on 2020-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_messagemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
