# Generated by Django 2.2.13 on 2020-07-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200719_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
